force-app/main/default/objects/StagingTable__c/StagingTable__c.object-meta.xml
<CustomObject>
    <label>StagingTable</label>
    <nameField>
        <label>StagingTable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StagingTables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StagingTable__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Electronic</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Book</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StagingTable__c/fields/isOrderable__c.field-meta.xml
<CustomField>
    <fullName>isOrderable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isOrderable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/StagingTable__c/fields/ProductSku__c.field-meta.xml
<CustomField>
    <fullName>ProductSku__c</fullName>
    <label>ProductSku</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StagingTable__c/fields/RecordStatus__c.field-meta.xml
<CustomField>
    <fullName>RecordStatus__c</fullName>
    <label>RecordStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StagingTable__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Stereo</fullName>
            </value>
            <value>
                <fullName>Headphone</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceProcessController.cls
/**
 * @description       : Controller Service Process
 * @author            : Christian Niro
 * @group             : Christian  Niro
 * @last modified on  : 05-22-2024
 * @last modified by  : 
 **/
public with sharing class ServiceProcessController{
    public static final String TEMPLATE = 'SendCsv';
    public static final String HEADERS = 'Id,Description,ProductSku,ProductCode,Class,Type,RecordStatus,isActive,isOrderable';
    @AuraEnabled
    public static void sendMail(){
        String body = '';
        String objectName = 'StagingTable__c';
        String condition = 'RecordStatus__c = :bind  LIMIT 50000';
        Map<String, Object> binds = new Map<String, Object>{ 'bind' => 'New' };

        List<StagingTable__c> recordList = QueryClass.queryHelperMethod(binds, objectName, condition, QueryClass.SYSTEM_MODE, false);

        for (StagingTable__c record : recordList){

            body += '' + record.Id + ',' + record.Description__c + ',' + record.ProductSku__c + ',' + record.ProductCode__c + ',' + record.Class__c + ',' + record.Type__c + ',' + record.RecordStatus__c + ',' + record.isActive__c + ',' + record.isOrderable__c + '\n';
        }

        String finalFile = HEADERS + '\n' + body;
        Blob fileBody = Blob.valueOf(finalFile);

        Id customTemplate = [SELECT Id, DeveloperName
                             FROM EmailTemplate
                             WHERE DeveloperName = :TEMPLATE].Id;

        UtilsClassEmail.sendMailCustomTemplate(customTemplate, fileBody, 'newStagingAreaRecords.csv', 'ServiceProcess', 'christianniro18@gmail.com', null);
    }

    @AuraEnabled
    public static List<StagingTable__c> getRecords(){


        String objectName = 'StagingTable__c';
        String condition = 'RecordStatus__c = :bind  LIMIT 50000';
        Map<String, Object> binds = new Map<String, Object>{ 'bind' => 'New' };

        List<StagingTable__c> recordList = QueryClass.queryHelperMethod(binds, objectName, condition, QueryClass.SYSTEM_MODE, false);

        System.debug('<<<record retrurn size' + recordList.size());


        if (recordList.isEmpty() || recordList == null){

            throw new QueryException('No records found in the database.');
        }


        return recordList;
    }

    @AuraEnabled
    public static String getContentFile(String documentId, Boolean thirdStep){
        // Recupera il ContentVersion dal documento ID
        Blob file = null;
        try{
            file = [SELECT VersionData
                    FROM ContentVersion
                    WHERE ContentDocumentId = :documentId AND IsLatest = true
                    LIMIT 1].VersionData;

            if (!Test.isRunningTest()){
                throw new ServiceCreationException('il File è vuoto');

            }


            return file.toString();
        } catch (Exception e){

            if (AMP_UtilsClass.limitHeap() == 0 || e.getMessage() == 'String length exceeds maximum: 6000000'){
                if (file != null){
                    AMP_UtilsClass.uploadFileAsync(file, thirdStep);
                } else{
                    throw new ServiceCreationException('il File è vuoto');
                }
            }
            throw new ServiceCreationException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Integer getContentSize(String documentId){
        return [SELECT ContentSize
                FROM ContentVersion
                WHERE ContentDocumentId = :documentId AND IsLatest = true
                LIMIT 1].ContentSize;
    }

    @AuraEnabled
    public static String uploadFile(Blob csv, Boolean thirdStep){
        String result = '';

        try{

            System.debug('Boolean' + thirdStep);

            AMP_UtilsClass.manageUploadFile(csv.toString(), thirdStep);
            result = 'Il caricamento del file si è completato con successo';
        } catch (Exception e){


            throw new InvalidStateCsvParseClassException(e.getMessage());
        }
        return result;
    }

}